### ISSUE TITLE
Rendre les ressources de type "famille" interruptibles

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-api#23]
Quand le demandeur indique qu'il ne percevra plus, par exemple, le CLCA lors du mois en cours, le mapping ignore cette information et projette malgré tout les montants perçus. 

Après investigation, c'est probablement dû au fait que interruptedRessources est une variable individu, et n'est pas lue quand on examine les ressources de type "famille".

**Comment by MattiSG** [comment]
Sera peut-être corrigé via sgmap/mes-aides-ui#22.

**Comment by guillett** [comment]
Implemented by sgmap/mes-aides-ui#628.
