### ISSUE TITLE
Ne pas injecter les prestations simulées dans la BR CMUC/ACS

### ISSUE THREAD

**Issue by Anne-LaureM** [sgmap/mes-aides-api#28]
En tant que bénéficiaire de la CMUC qui vient juste d'avoir 65 ans, je suis maintenant éligible à l'ASPA. L'ASPA ne doit pas être injectée dans la BR CMUC car je ne la touchais pas sur les 12 derniers mois et ce droit est ouvert pour un an.
En tant que bénéficiaire de la CMUC qui vient d'avoir un enfant, je suis maintenant éligible à l'ASF. L'ASF ne doit pas être injectée dans la BR CMUC car je ne la touchais pas sur les 12 derniers mois et ce droit est ouvert pour un an.

**Comment by fpagnoux** [comment]
@Anne-LaureM:
Est-ce que tu confirmes que ce problème a bien été corrigé par #29 ? 
Merci !

**Comment by Anne-LaureM** [comment]
Les deux tests sont encore rouges: test sur une [ASPA non perçue] (https://mes-aides.gouv.fr/tests/5531000aae99f06b16440f0d/show?keyword=cmu-c%252Facs)

**Comment by fpagnoux** [comment]
Ce test semble indiquer que le demandeur doit reçevoir à la fois la CMU et l'ACS. Tu confirmes que c'est une erreur et qu'on attend que la CMU ?

**Comment by Anne-LaureM** [comment]
Effectivement on attend uniquement la CMUC

**Comment by fpagnoux** [comment]
Correction déployée. 
La CMU ne se basait pas sur les prestations injectées, mais continuait d'estimer les 12 derniers mois à partir du mois M.
