### ISSUE TITLE
Neutraliser les revenus n-2 si le demandeur déclare du RSA socle

### ISSUE THREAD

**Issue by Anne-LaureM** [sgmap/mes-aides-api#33]
En tant que bénéficiaire du RSA socle,

Je peux déclarer percevoir du RSA socle et voir mes ressources n-2 neutralisées

pour le calcul de mes AL.

- [x] wiki

**Comment by HelaG** [comment]
Neutralisation à 100% des revenus N-2 dans le calcul des APL d'un bénéficaire du RSA.

Cette mesure suppose que le montant du RSA déclaré dans la capture des ressources soit modifié ( hypoyhèse à confirmer auprès des experts Caf).
Le montant d'AL calculé (avec des ressources n-2 = 0) doit être ajouté à la BR du RSA.

**Comment by HelaG** [comment]
Le montant du RSA est modifié uniquement si le montant des AL simulées est supérieur au forfait logement impacté dans la BR RSA.

**Comment by HelaG** [comment]
Test : https://mes-aides.gouv.fr/tests/?state=pending

**Comment by fpagnoux** [comment]
@helag, @mattisg, @cbenz @eraviart

L'implémentation pose un problème intéressant  pour le simulateur. 
On introduit ici une dépendance de l'AL(m) vers le RSA(m-1). Or le RSA(m-1) dépend de AL(m-1), AL(m-2) et AL(m-3). 
Le simulateur va donc se lancer dans une course infinie vers la nuit des temps, et exploser. 

Vous avez des idées sur une solution ? Vous avez déjà rencontré le problème ? 

Pour moi, le comportement attendu dans ce cas précis - mais je ne sais pas si c'est généralisable à tout problème de dépendance cyclique -  serait le suivant : 
- On cherche à savoir si le demandeur a reçu du RSA au mois m-1
- Si une valeur a déjà été renseignée (vraisemblablement car rentrée en input), on prend cette valeur. Si non, on ne fait **pas de calcul**, et on renvoie la valeur par défaut.

Côté openfisca, ça voudrait dire qu'on a une variante à `calculate` qui s'appellerait quelque chose du genre `get_value_if_already_known()` et qui irait chercher la valeur en s'interdisant d'utiliser la formule.

**Comment by MattiSG** [comment]
D'un point de vue usager / fiabilité des calculs, je ne sais pas ce qui fait le plus de sens.
Il y a une vraie question OpenFisca sur la gestion des dépendances cycliques décalées temporellement.
