### ISSUE TITLE
Appliquer une évaluation forfaitaire des ressources pour les TNS

### ISSUE THREAD

**Issue by Anne-LaureM** [sgmap/mes-aides-api#34]
En tant que travailleur non salarié ayant subi un changement de situation depuis n-2,

Je peux bénéficier d'une évaluation forfaitaire de mes ressources,

Pour le calcul de mon AL

**Comment by HelaG** [comment]
Pour un TNS dont les ressources m-1 sont < 1015 fois le SMIC horaire du 31/12 de l'année N-2, alors on applique une [évaluation forfaitaire](http://legislation.openfisca.fr/variables/aide_logement_base_ressources_eval_forfaitaire) de ses ressources.

**Comment by HelaG** [comment]
Test : https://mes-aides.gouv.fr/tests/55c0ee462cdf295972b4f19f/show

**Comment by MattiSG** [comment]
Doublon de sgmap/openfisca-france#16, plus détaillé mais dans le mauvais dépôt.
