### ISSUE TITLE
Mettre à jour Node.js

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-api#37]
Passer à la dernière version de Node v0.12 — EDIT : v6.

**Comment by MattiSG** [comment]
Issue with `concat`, documented in sgmap/mes-aides-ui#159.

**Comment by MattiSG** [comment]
Mettre à jour à Node v6. Attention, cela va certainement tirer la mise à jour de plusieurs paquets.

**Comment by guillett** [comment]
Bye bye 0.10, hello 6.x.

Fixed by #113
