### ISSUE TITLE
PLF - Gérer les enfants handicapés de plus de 25 ans

### ISSUE THREAD

**Issue by Anne-LaureM** [sgmap/mes-aides-api#39]
En tant que demandeur de PLF ayant un enfant handicapé de plus de 25 ans, 
Je peux le déclarer dans le simulateur,
Afin de déterminer mon éligibilité

**Comment by Anne-LaureM** [comment]
Prendre en compte seulement si pas de revenus pros pour l'enfant

**Comment by HelaG** [comment]
Communication [twitter](https://twitter.com/MesAides/status/625982397738258432) et Mairie de Paris.
