### ISSUE TITLE
Ne pas afficher de RSA majoré pour une personne isolée depuis plus de 12 mois

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-api#47]
En tant que personne isolée depuis plus de 12 mois,

Je peux indiquer la durée de ma situation d'"isolement",

Pour voir apparaitre un résultat de RSA exact.

**Comment by HelaG** [comment]
Une personne a droit à du RSA majoré pendant 12 mois sur les 18 mois à compter de la date de début de la situation d'isolement 

Aujourd'hui le simulateur affiche [systématiquement du RSA majoré](https://wiki.openfisca.fr/index.php/RSA#R.C3.A8gles_de_calcul) quelque soit la durée de la situation d'isolement.

**Comment by HelaG** [comment]
Cas de recette : 
- https://mes-aides.gouv.fr/tests/559e5ba1d7483c5f013a983c/show?keyword=recette
- https://mes-aides.gouv.fr/tests/559fbdbb186ae5620110e28b/show?keyword=recette

**Comment by MattiSG** [comment]
Doublon de #156.
