### ISSUE TITLE
Ne pas vérifier la condition de "parisianité" pour un usager sans domicile stable

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-api#48]
En tant qu'usager sans domicile stable,

Je peux directement passer à l'étape suivante sans répondre à la question des 3 dernières années à Paris, 

Pour avoir une navigation plus fluide.

**Comment by MattiSG** [comment]
Doublon de sgmap/mes-aides-ui#139.

(merci @HelaG  :)  )
