### ISSUE TITLE
Aligner les résultats de la Prime d'activité avec le simulateur de la CAF

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-api#70]
2 retours utilisateurs qui font état de résultats différents entre Mes Aides et le simulateur Caf pour la Prime d'activté. 

Cf [test](https://mes-aides.gouv.fr/tests/56a12778cd1a2836487486ca/show) 

Comm :
- [x] Mail du 21/01 à 1:14PM
- [ ] Mail du 27/01 à 5:03PM

**Comment by fpagnoux** [comment]
Le RSA est cumulable avec la PPA pour les bas salaires, confirmé par les simulateurs CAF et de vive voix par la DGCS.
Je peux fermer l'issue ?

**Comment by MattiSG** [comment]
Répondre au mail référencé au-dessus, et lier vers un test Ludwig / un descriptif de situation pour prouver plus tard le cas échéant.

**Comment by HelaG** [comment]
Répondre au mail : DONE (avec lien vers cette issue) 

Est-ce qu'on peut simplement renommer l'issue, que l'utilisatrice puisse éventuellement retrouver nos échanges?

**Comment by MattiSG** [comment]
Je ne sais pas vers quoi tu veux la renommer, je te laisse le faire en cliquant sur "Edit" à droite du nom de l'issue  :wink:

**Comment by HelaG** [comment]
J'ai pas trouvé mieux...

**Comment by MattiSG** [comment]
Oh… du coup le scope est très considérablement élargi. On en parle tout à l'heure ?

**Comment by HelaG** [comment]
Oui... Je le passe en sprint backlog, l'idée étant de répartir cette issue en différents tickets pour corriger les écarts.

**Comment by fpagnoux** [comment]
Issue trop vague qui traîne depuis trop longtemps.
