### ISSUE TITLE
Prioriser la PAJE sur le CF

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-api#76]
En tant que bénéficiaire potentiel éligible à la PAJE et au CF, 
Mes-aides m'indique que je ne suis éligible qu'à la PAJE, 
Car le elle est toujours prioritaire sur le CF, même si moins favorable.

**Comment by fpagnoux** [comment]
Règle remontée de la CAF 44.
Peut être à confirmer ?

**Comment by benjello** [comment]
Mais si la personne ne demande pas la PAJE et ne demande que le CF ?

**Comment by fpagnoux** [comment]
En fait la CAF te verse automatiquement les prestations familiales, la majorité sont versées automatiquement. Donc tant que ton enfant aura moins de 3 ans tu recevras de la PAJE.

**Comment by benjello** [comment]
Parfait donc.

**Comment by fpagnoux** [comment]
Doublon de https://github.com/sgmap/mes-aides-api/issues/71.
