### ISSUE TITLE
Impossible de valider la page d'informations complémentaires

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-api#77]
En fin de simulation impossible de valider la page :

- https://mes-aides.gouv.fr/infos-complementaires?droit=acs
- OS : Mac dernière version
- Navigateur : Chrome Version 48.0.2564.103 (64-bit) 
- Log console :

```
d42f0e83.vendor.js:2 TypeError: Cannot read property 'situationFamiliale' of undefined
    at Object.createApiCompatibleSituation (b75f012a.scripts.js:2)
    at Object.save (b75f012a.scripts.js:2)
    at k.a.submit (b75f012a.scripts.js:2)
    at d42f0e83.vendor.js:4
    at e (d42f0e83.vendor.js:5)
    at k.$eval (d42f0e83.vendor.js:2)
    at k.$apply (d42f0e83.vendor.js:2)
    at HTMLFormElement.<anonymous> (d42f0e83.vendor.js:5)
    at d42f0e83.vendor.js:1
    at f (d42f0e83.vendor.js:1)(anonymous function) @ d42f0e83.vendor.js:2
```

- [ ] Répondre au mail du 08/02 à 17h31

**Comment by fpagnoux** [comment]
J'ai l'impression que ce problème ne se pose que si on ouvre "Engager les démarches" dans un nouvel onglet. Le contexte de la situation n'est a priori pas transmis, d'où l'erreur.
@MattiSG, si je me souviens bien, tu avais déjà évoqué ce point lors d'une discussion. 

Pas sûr que ça vaille le coût de faire quelque chose pour éviter ce bug...

**Comment by MattiSG** [comment]
Si c'est le cas, alors effectivement on ne peut pas en sortir : on utilise `sessionStorage` et non `localStorage` justement pour permettre d'avoir plusieurs simulations en parallèle dans plusieurs onglets, ce qui implique forcément que chaque onglet ait une situation différente.
