### ISSUE TITLE
Ne pas appliquer de pente aux IJ au delà du 3e mois

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-api#80]
En tant que bénéficiaire potentiel à la prime d'activité,
Je peux déclarer que je perçois des IJ depuis plus de 3 mois,
Pour que mes ressources de remplacement soient correctement prises en compte et que le calcul de mon droit soit exact

**Comment by fpagnoux** [comment]
IJ maternité et paternité:  revenu d'activité sans limite de durée.
IJ cumulé à un revenu d'activité: revenu d'activité sans limite de durée.
IJ maladie, maladie pro ou accident de travail: revenu d'activité les 3 premiers mois seulement, seulement si elles se substituent à un salaire (pas au chômage).

**Comment by fpagnoux** [comment]
Pour implémenter correctement le comportement, si une personne indique percevoir des IJ,  mais pas de salaire, il faudrait lui demander de quand date son arrêt de travail.
Est-ce que cette question supplémentaire vous paraît acceptable ?

@MattiSG @HelaG

**Comment by MattiSG** [comment]
Oui.

On pose déjà la question pour le cas du chômage — il serait pertinent d'uniformiser la présentation des questions. Pourquoi pas ne poser la question que si on déclare des ARE / IJ ?

**Comment by fpagnoux** [comment]
On pose une question similaire, mais pas tout à fait la même: fin du contrat de travail vs début de l'arrêt de travail.
Pour l'ARE non: un bénéficiaire de l'ASS doit avoir épuisé ses droits à l'ARE donc il faut poser la question *surtout* s'il n'en touche pas ;).

**Comment by fpagnoux** [comment]
+1  : Retour utilisateur du 23 juin 2016 à 10:57

**Comment by fpagnoux** [comment]
Sources:

[Suivi législatif RSA](http://www.gisti.org/IMG/pdf/circ_2012-27-06_cnaf-suivi-legislatif-rsa.pdf) page 72, paragraphe 5245
[Suivi législatif PPA](http://www.gisti.org/IMG/pdf/suivi-legislatif-prime-activite-date-juillet-2015.pdf) page 63
