### ISSUE TITLE
Indiquer que le montant des aides locales n'est pas pris en compte dans le calcul des aides nationales

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-api#83]
En tant que bénéficiaire potentiel à qui l'on annonce que je peux percevoir des aides locales et des aides nationales,
On m'indique que l'impact des premières n'est pas pris en compte sur les dernières,
Pour que je ne surestime pas les aides que je peux percevoir.

**Comment by MattiSG** [comment]
Ce serait pas plutôt dans sgmap/mes-aides-ui ?

**Comment by fpagnoux** [comment]
As you said.
