### ISSUE TITLE
Déployer en continu

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-api#90]
https://docs.travis-ci.com/user/deployment/npm

**Comment by MattiSG** [comment]
@fpagnoux Cela a-t-il du sens ? Il me semble qu'on installe via GitHub sur `master`, non ? 🤔

**Comment by fpagnoux** [comment]
Releaser sur npm, non, on passe effectivement pas les tags GitHub.

On pourrait automatiser la publication du tag, mais la valeur n'est pas gigantesque. 

Je me souviens m'être questionné sur cette issue, mais je ne me souviens plus des conclusions...

**Comment by MattiSG** [comment]
Donc le seul intérêt serait d'automatiser le tagging au merge sur master. Ça peut être utile, mais ça n'est pas cette issue.
